In [2]:
import numpy as np 

In [5]:
a = np.zeros( (5, 2) )
b = np.ones( (5,1) )
a, b

(array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1.],
        [1.],
        [1.],
        [1.],
        [1.]]))

In [7]:
np.hstack((a, b))

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])