In [1]:
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
width, height = 2000, 1000 


In [10]:
a = np.random.randint(0, 10, size=(5, 2)) * 10
b = np.random.randint(0, 10, size=(3,2)) * 10
c = np.random.randint(0, 10, (4, 2)) * 10
a, b, c

(array([[20, 20],
        [20, 30],
        [90, 80],
        [20, 70],
        [20, 50]]),
 array([[90, 40],
        [20, 30],
        [40, 30]]),
 array([[50, 60],
        [10,  0],
        [60, 10],
        [80, 30]]))

In [9]:
s = np.vstack([a, b, c])
s

array([[80, 70],
       [30, 80],
       [90, 50],
       [80, 70],
       [90,  0],
       [90, 10],
       [70, 10],
       [90, 90],
       [50, 20],
       [80, 40],
       [30, 70],
       [20,  0]])

In [26]:
# argsort() example
a = np.argsort(s[:,1])
a

array([ 4, 11,  5,  6,  8,  9,  2,  0,  3, 10,  1,  7], dtype=int64)

In [28]:
sa = s[a]
sa

array([[90,  0],
       [20,  0],
       [90, 10],
       [70, 10],
       [50, 20],
       [80, 40],
       [90, 50],
       [80, 70],
       [80, 70],
       [30, 70],
       [30, 80],
       [90, 90]])

In [19]:
# lexsort() returns array of indices in descending order
ii = np.lexsort( (s[:,1], s[:,0]) )
ii 

array([11, 10,  1,  8,  6,  9,  0,  3,  4,  5,  2,  7], dtype=int64)

In [21]:
s[11], s[10], s[1]

(array([20,  0]), array([30, 70]), array([30, 80]))

In [13]:
ss = s[ np.lexsort((s[:,1], s[:,0]))]
ss

array([[20,  0],
       [30, 70],
       [30, 80],
       [50, 20],
       [70, 10],
       [80, 40],
       [80, 70],
       [80, 70],
       [90,  0],
       [90, 10],
       [90, 50],
       [90, 90]])

In [6]:
s1 = s[ np.argsort(s[:, 1])]
s1 

array([[50,  0],
       [90,  0],
       [80,  0],
       [ 0, 10],
       [90, 20],
       [50, 20],
       [10, 20],
       [80, 20],
       [80, 60],
       [20, 60],
       [70, 70],
       [50, 70],
       [70, 70],
       [10, 70],
       [10, 80],
       [70, 80],
       [50, 90]])

In [7]:
s0 = s1[ np.argsort(s1[:,0], kind='stable')]
s0 

array([[ 0, 10],
       [10, 20],
       [10, 70],
       [10, 80],
       [20, 60],
       [50,  0],
       [50, 20],
       [50, 70],
       [50, 90],
       [70, 70],
       [70, 70],
       [70, 80],
       [80,  0],
       [80, 20],
       [80, 60],
       [90,  0],
       [90, 20]])