In [1]:
import numpy as np 
import matplotlib.pyplot as plt 

In [35]:
width, height = 2000, 1000 


array([[1846,  871],
       [ 465,  154],
       [1325,  646],
       [1579,  561]])

In [76]:
a = np.random.randint(0, 10, size=(10, 2)) * 10
b = np.random.randint(0, 10, size=(3,2)) * 10
c = np.random.randint(0, 10, (4, 2)) * 10

In [77]:
s = np.vstack([a, b, c])
s

array([[30, 30],
       [50, 30],
       [40, 80],
       [ 0, 40],
       [40, 10],
       [20, 60],
       [60, 10],
       [90, 70],
       [30, 30],
       [80,  0],
       [10, 90],
       [70, 20],
       [ 0, 70],
       [50, 50],
       [20, 20],
       [90,  0],
       [20, 20]])

In [78]:
ss = s[ np.lexsort((s[:,1], s[:,0]))]
ss

array([[ 0, 40],
       [ 0, 70],
       [10, 90],
       [20, 20],
       [20, 20],
       [20, 60],
       [30, 30],
       [30, 30],
       [40, 10],
       [40, 80],
       [50, 30],
       [50, 50],
       [60, 10],
       [70, 20],
       [80,  0],
       [90,  0],
       [90, 70]])

In [80]:
s1 = s[ np.argsort(s[:, 1])]
s1 

array([[80,  0],
       [90,  0],
       [40, 10],
       [60, 10],
       [20, 20],
       [20, 20],
       [70, 20],
       [30, 30],
       [50, 30],
       [30, 30],
       [ 0, 40],
       [50, 50],
       [20, 60],
       [ 0, 70],
       [90, 70],
       [40, 80],
       [10, 90]])

In [83]:
s0 = s1[ np.argsort(s1[:,0], kind='stable')]
s0 

array([[ 0, 40],
       [ 0, 70],
       [10, 90],
       [20, 20],
       [20, 20],
       [20, 60],
       [30, 30],
       [30, 30],
       [40, 10],
       [40, 80],
       [50, 30],
       [50, 50],
       [60, 10],
       [70, 20],
       [80,  0],
       [90,  0],
       [90, 70]])